firstdjango/firstdjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('picture/', include('picture.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstdjango/picture/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# 指定应用名称
app_name = 'picture'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('id/<int:Picture_id>', views.PictureID_view, name='PictureID'),
    path("info", views.info_view, name='info'),
    path("url", views.url_view, name='url'),
    path('filter', views.filter_view, name='filter'),
    path("template", views.template_view, name='template'),
    path("sta", views.static_view, name='static'),

]

firstdjango/picture/models.py
from django.db import models

# Create your models here.

firstdjango/picture/views.py
from django.shortcuts import render, HttpResponse
from datetime import datetime

# Create your views here.

def index_view(requests):
    return render(requests, template_name="index.html")


def PictureID_view(request, Picture_id):
    Picture_id = int(Picture_id)

    return HttpResponse(f"现在的图片ID是{Picture_id}")


def info_view(requests):
    username = "大大怪"
    military_rank = "将军"

    xiashu_dic = {
        "name": "小小怪",
        "military_rank": "下士",
    }

    context = {"username": username, "military_rank": military_rank, "xiashu_dic": xiashu_dic}

    return render(requests, template_name="info.html", context=context)

def url_view(requests):

    return render(requests, template_name="url.html")

def filter_view(requests):

    green = "Hello World"

    context = {
        "green": green,
        "birthday": datetime.now(),
        "profile": ""
    }
    return render(requests, template_name="filter.html", context=context)

def template_view(requests):

    context = {
        "articles": ["小米suv7", "开心超人" ]
    }
    return render(requests, template_name="xfz_index.html", context=context)

def static_view(requests):

    return render(requests, template_name="static.html")

firstdjango/templates/filter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p> 生日: {{ birthday|date:"Y-m-d" }}</p>
<p> 个人简介: {{ profile|default:"这个家伙很懒，什么都没留下" }}</p>
</body>
</html>

firstdjango/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<p> Hello World</p>
<body>

</body>
</html>

firstdjango/templates/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p> 姓名：{{ username }}</p>
<p> 军衔：{{ military_rank }}</p>
<p> 下属 </p>
<p> 姓名：{{ xiashu_dic.name }}</p>
<p> 军衔：{{ xiashu_dic.military_rank }}</p>
</body>
</html>

firstdjango/templates/static.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>加载静态文件</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="{% static 'js/index.js' %}"></script>
</head>
<body>
<h1> 大秦 </h1>
</body>
</html>

firstdjango/templates/url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url "picture:info" %}"> 开心超人 </a>
</body>
</html>

firstdjango/templates/xfz_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}-不良人</title>
    {% block head %}{% endblock %}
</head>
<body>
<header>
    <ul>
        <li><a href="/"> 首页 </a></li>
        <li><a href="/course"> 创业课堂 </a></li>
    </ul>
</header>
{% block body %}
    我是来自父模板的东东
{% endblock %}
</body>
</html>

firstdjango/templates/xfz_hotarticle.html
<div>
    <li>文章1</li>
    <li>文章2</li>
    <h2> 热门文章</h2>
    <ul>
        {% for article in articles %}
            <li>{{ article }}</li>
        {% endfor %}


    </ul>
</div>

firstdjango/templates/xfz_index.html
{% extends "xfz_base.html" %}

{% block title %}首页{% endblock %}
{% block head %}
	<style>
    body{
        background-color: pink;
    }
    </style>
{% endblock %}

{% block body %}
	{% include "xfz_hotarticle.html" %}
    <div>
    不良人
    </div>
    {{ block.super}}
{% endblock %}